   [[providers]]
  name = "reddit"
  aliases = ["r"]
  url = "https://www.reddit.com/search/?q={{query}}"
  icon = ""
  tag_bg = "#FF4500"
  icon_color = "#FFFFFF"
  text_color = "#FFFFFF"

  [[providers]]
  name = "chatgpt"
  aliases = ["c", "gpt"]
  url = "https://chatgpt.com/?q={{query}}"
  icon = "⌬"
  tag_bg = "#10A37F"
  icon_color = "#FFFFFF"
  text_color = "#FFFFFF"
